language: node_js

sudo: true

addons:
  chrome: beta

node_js:
  - '8'
  - '10'

branches:
  only:
  - master

cache: yarn

before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9333 http://localhost &

matrix:
  fast_finish: true

install:
  - npm install

notifications:
  email: true

script:
  - npm run test
